name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Install Go dependencies
      run: |
        cd src
        go mod tidy

    - name: Run unit tests
      run: |
        cd src
        go test -v

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

        minikube version
        rm minikube-linux-amd64

    - name: Start Minikube Cluster
      run: |
        minikube start --driver=docker

        # Set up kubectl to use Minikube's context
        kubectl config use-context minikube

        # Debug: Check kubeconfig file content
        kubectl config view

    - name: Install kubectl
      run: sudo apt-get install -y kubectl

    - name: Run kubectl commands
      run: |
        kubectl get nodes

    - name: Build
      uses: werf/actions/build@v2

    - name: Run acceptance tests
      uses: werf/actions/run@v2
      with:
        image: app-test-4
        args: curl -v -f http://localhost:8000 || exit 1
      env:
        WERF_DOCKER_OPTIONS: "-d -p 8000:8000"
